### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by grahamdyson** [adambisek/string-pixel-width#15]
Hi, 

Thought I'd let you/people know I've created a TypeScript definition for this package:

https://www.npmjs.com/package/@types/string-pixel-width
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/0558f655978ed0d3fd46207d9a6d59adf8d041cb

Cheers,
Graham

**Comment by adambisek** [comment]
:)
