### ISSUE TITLE
Guide for adding a new font?

### ISSUE THREAD

**Issue by nsonnad** [adambisek/string-pixel-width#3]
Hello! Thanks for this tool, I have been trying to solve this problem forever. I was wondering if you'd be able to provide some guidance on how to add a custom font, and maybe allow a kind of plugin system that allows you to pass in a custom font size map? If you can show me how to get the map, I'd be happy to submit a PR for the second part. Thanks!

**Comment by adambisek** [comment]
HI, I've added the guide for you - https://github.com/adambisek/string-pixel-width#how-to-contribute. Enjoy!

Have great day,
Adam
