### ISSUE TITLE
Export as ES5 module

### ISSUE THREAD

**Issue by acailly** [adambisek/string-pixel-width#5]
Today many build config does not support ES6 modules because it uses an old version of Uglify.

This is the case for `create-react-app` (see [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify))

Until `uglify-es` use spreads (see [here](https://github.com/facebookincubator/create-react-app/issues/2108)), would it be possible to distribute this lib as an ES5 module ?

**Comment by adambisek** [comment]
Yes, it is, because published version is always compiled to ES5.
When you install it via ```npm i string-pixel-width --save```, it will work.

**Comment by acailly** [comment]
Actually only ES6 missing features of Node v6 are compiled because it uses es2015-node6/object-rest preset. This means this lib can't be used un the browser.

**Comment by adambisek** [comment]
Ohh, sorry, didn't realize that.
Which preset exactly would help you?

**Comment by acailly** [comment]
The preset `es2015` should contains all es6 features

**Comment by adambisek** [comment]
Version 1.2.0 is out. Should work for you now :)

**Comment by acailly** [comment]
It works! Thank you.
